# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: 'Junit'
   displayName: 'rama'
   jobs:
     - job: 'JunitTest'
       displayName: 'jtest'
       steps:
         - script: echo 'you runjunit test'
         - task: Maven@1
           inputs:
             mavenPomFile: 'pom.xml'
             goals: 'mytest1'
             publishJUnitResults: true
             testResultsFiles: '**/TEST-*.xml'
             testRunTitle: 'ok1'
             codeCoverageToolOption: 'JaCoCo'
             javaHomeOption: 'JDKVersion'
             mavenVersionOption: 'Default'
             mavenAuthenticateFeed: true
             sonarQubeRunAnalysis: false
             checkStyleRunAnalysis: true
             pmdRunAnalysis: true

  
  
  